name: Publish Multiarch Image - Daily

on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: "10 3 * * *" # RUN @3:10 UTC Everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

      - name: Download EarnApp
        run: wget -cq https://brightdata.com/static/earnapp/bin_64 -O ./earnapp && chmod a+x ./earnapp

      - name: Get version
        run: echo $(./earnapp --version) > ./version

      - name: Remove escape sequences
        run: sudo apt install dos2unix -y && dos2unix ./version

      - name: Build & Push - Latest Regular
        run: |
          docker buildx build --push \
          -t raduvalentingmail/earnapp:latest \
          -t raduvalentingmail/earnapp:$(cat ./version) \
          --platform linux/amd64,linux/arm/v7,linux/arm64 build/app
      - name: Build & Push - Latest Lite
        run: |
          docker buildx build --push \
          -t raduvalentingmail/earnapp:lite \
          -t raduvalentingmail/earnapp:lite-$(cat ./version) \
          --platform linux/amd64,linux/arm/v7,linux/arm64 build/lite

      - name: Update Docker Hub Readme
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: raduvalentingmail/earnapp
          short-description: UNOFFICIAL image for BrightData's EarnApp.
          readme-filepath: DOCKERHUB_README.md
