name: Debian Build

on:
  workflow_dispatch:
  # push:
  # schedule:
  #   - cron: "10 3 * * *" # RUN @3:10 UTC Everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKERUSER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
        run: |
          echo $( $DOCKER_USER )
          echo $( $DOCKER_PASSWORD )
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          

      - name: Download EarnApp
        run: wget -cq https://brightdata.com/static/earnapp/bin_64 -O ./earnapp && chmod a+x ./earnapp

      - name: Get version
        run: echo $(./earnapp --version) > ./version

      - name: Remove escape sequences
        run: sudo apt install dos2unix -y && dos2unix ./version

      - name: Build & Push - Debian
        run: |
          docker buildx build --push \
          -t raduvalentingmail/earnapp:debian \
          -t raduvalentingmail/earnapp:debian-$(cat ./version) \
          --platform linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64 build/debian
